App:
  ListenerAddress: 0.0.0.0:8081
  WorkDir: ./.workdata

Cess:
  RpcUrl: wss://testnet-rpc0.cess.cloud/ws/
  SecretPhrase : "tray fine poem nothing glimpse insane carbon empty grief dismiss bird nurse"

Cessfsc:
  BootAddrs:
    - "_dnsaddr.boot-kldr-testnet.cess.cloud"
  P2pPort: 138001